- name: test puppet
  hosts: localhost
  connection: local
  strategy: free
  remote_user: root
  gather_facts: false

  tasks:
  - name: test puppet agent
    puppet_agent:
      state: run
      noop: true

  - name: test puppet apply
    puppet_apply:
      manifest: foo.pp
      noop: true
