- name: test puppet
  hosts: localhost
  connection: local
  strategy: free
  remote_user: root
  gather_facts: false

  tasks:
  - name: test puppet
    puppet_agent:
      state: run
      noop: true
